import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const recoleta = localFont({
  src: [
    {
      path: "./fonts/recoleta/Recoleta-Black.ttf",
      weight: "900",
    },
    {
      path: "./fonts/recoleta/Recoleta-Bold.ttf",
      weight: "800",
    },
    {
      path: "./fonts/recoleta/Recoleta-Semibold.ttf",
      weight: "600",
    },
    {
      path: "./fonts/recoleta/Recoleta-Medium.ttf",
      weight: "500",
    },
    {
      path: "./fonts/recoleta/Recoleta-Regular.ttf",
      weight: "400",
    },
    {
      path: "./fonts/recoleta/Recoleta-Thin.ttf",
      weight: "300"
    }
  ],
  variable: "--font-recoleta",
});


const recoletaAlt = localFont({
  src: [
    {
      path: "./fonts/recoletaAlt/RecoletaAlt-Black.ttf",
      weight: "900",
    },
    {
      path: "./fonts/recoletaAlt/RecoletaAlt-Bold.ttf",
      weight: "800",
    },
    {
      path: "./fonts/recoletaAlt/RecoletaAlt-Semibold.ttf",
      weight: "600",
    },
    {
      path: "./fonts/recoletaAlt/RecoletaAlt-Medium.ttf",
      weight: "500",
    },
    {
      path: "./fonts/recoletaAlt/RecoletaAlt-Regular.ttf",
      weight: "400",
    },
    {
      path: "./fonts/recoletaAlt/RecoletaAlt-Light.ttf",
      weight: "300"
    },
    {
      path: "./fonts/recoletaAlt/RecoletaAlt-Thin.ttf",
      weight: "200"
    }
  ],
  variable: "--font-recoletaAlt",
});

const prompt = localFont({
  src: [
    {
      path: "./fonts/prompt/Prompt-Black.ttf",
      weight: "900",
    },
    {
      path: "./fonts/prompt/Prompt-Bold.ttf",
      weight: "800",
    },
    {
      path: "./fonts/prompt/Prompt-Semibold.ttf",
      weight: "600",
    },
    {
      path: "./fonts/prompt/Prompt-Medium.ttf",
      weight: "500",
    },
    {
      path: "./fonts/prompt/Prompt-Regular.ttf",
      weight: "400",
    },
    {
      path: "./fonts/prompt/Prompt-Light.ttf",
      weight: "300"
    },
    {
      path: "./fonts/prompt/Prompt-Thin.ttf",
      weight: "200"
    }
  ],
  variable: "--font-prompt",
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${recoleta.variable} ${recoletaAlt.variable} ${prompt} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
